### ISSUE TITLE
Implement test function for ddpg

### ISSUE THREAD

**Issue by whikwon** [kairproject/kair_algorithms_draft#3]
No available test function in ddpg now.

**Comment by Curt-Park** [comment]
AbstractAgent 안에 test 함수가 구현되어 있습니다.
단, test시에 action에 noise를 제외시키는 부분은 구현되어야합니다.

https://github.com/kairproject/kair_algorithms_draft/blob/master/scripts/algorithms/common/abstract/agent.py#L89
