### ISSUE TITLE
Duplicate random seed location 

### ISSUE THREAD

**Issue by whikwon** [kairproject/kair_algorithms_draft#5]
random seed를 지정해주는 위치가 2군데 있는데 바깥으로 몰아버리는게 낫지 않을까 합니다. 

https://github.com/kairproject/kair_algorithms_draft/blob/7f4756a1d466110b739bb93b46851ba505481c43/scripts/run_lunarlander_continuous.py#L56-L58

https://github.com/kairproject/kair_algorithms_draft/blob/7f4756a1d466110b739bb93b46851ba505481c43/scripts/algorithms/common/noise.py#L26

**Comment by seungjaeryanlee** [comment]
찬성해요! `set_seed()` 같은 함수 하나 만들면 어떨까요?

**Comment by whikwon** [comment]
좋습니다. 지원해주실 분!

**Comment by MrSyee** [comment]
제가 추가해놓겠습니다!

**Comment by whikwon** [comment]
Closed by @MrSyee
