### ISSUE TITLE
DDPG performance for LunarLanderContinuous,v2

### ISSUE THREAD

**Issue by whikwon** [kairproject/kair_algorithms_draft#6]
@Curt-Park @MrSyee DDPG 학습 시 `actor_loss`는 마이너스로 계속 내려가고 `critic_loss`는 2000~3000대에서 머무르면서 score variation이 매우 심한데 원래 이런가요?

baseline 알고리즘 성능이랑 비교가 필요하다고 생각이 듭니다. 

https://github.com/medipixel/reinforcement_learning_examples 기준으로 확인했고 episode는 300회 정도 학습시켰습니다.

**Comment by Curt-Park** [comment]
네 다소 성능에 널뛰기가 있습니다. fD나 BC를 붙이면 꽤 안정되는 모습을 보이구요.
1500번 돌린 로그입니다.
https://app.wandb.ai/curt-park/ddpg/runs/el0k820a

**Comment by Curt-Park** [comment]
조만간 다른 구현도 참고하여 다시 뜯어보도록 하겠습니다.

**Comment by whikwon** [comment]
공유 감사합니다. 성능 널뛰기가 엄청 심하군요. 이번주에 알고리즘 간에 성능 확인 방식(env, # of seeds, reference papers...)을 정하면 좋을거 같습니다.
(관련 철희님께서 공유하셨던 논문: https://arxiv.org/pdf/1709.06560.pdf)

**Comment by whikwon** [comment]
mujoco 성능과 비교하기로 결정. (각 논문에 기재된 성능)
