### ISSUE TITLE
Add action boundary value from environment 

### ISSUE THREAD

**Issue by whikwon** [kairproject/kair_algorithms_draft#7]
현재 min_action, max_action 범위가 하드 코딩되어 전달이 되는데 environment로부터 받아서 관리하거나 `scripts/examples/env/` 에서 받도록 변경하면 좋을 것 같습니다. 
https://github.com/kairproject/kair_algorithms_draft/blob/7f4756a1d466110b739bb93b46851ba505481c43/scripts/algorithms/ddpg/agent.py#L89

**Comment by Curt-Park** [comment]
이미 처리되어 있습니다. 내부 로직에서는 무조건 (-1, 1) 범위로만 처리해주면 됩니다. (사실 action 함수에서 clipping해주므로 별도의 clipping을 안해줘도 무방하긴 합니다.)
https://github.com/kairproject/kair_algorithms_draft/blob/7f4756a1d4/scripts/algorithms/common/abstract/agent.py#L115
